-- Migration 016: Multi-TP Targets & Auto-Breakeven Stop Loss Support
-- Adds TP1, TP2, TP3 targets and Auto-Breakeven flags to watchlist and trades tables.

ALTER TABLE watchlist_items
ADD COLUMN IF NOT EXISTS tp1_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp2_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp3_price NUMERIC,
ADD COLUMN IF NOT EXISTS auto_be_on_tp1 BOOLEAN DEFAULT TRUE;

ALTER TABLE trade_alerts
ADD COLUMN IF NOT EXISTS tp1_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp2_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp3_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp1_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tp2_hit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS auto_be_on_tp1 BOOLEAN DEFAULT TRUE;

ALTER TABLE archived_trade_alerts
ADD COLUMN IF NOT EXISTS tp1_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp2_price NUMERIC,
ADD COLUMN IF NOT EXISTS tp3_price NUMERIC,
ADD COLUMN IF NOT EXISTS auto_be_on_tp1 BOOLEAN DEFAULT TRUE;
